version: "3.8"

services:

  app-backend:
    build:
      context: services/backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./services/backend:/backend
    command: ["sails", "lift", "--silly", "--drop"]
    ports:
      - 1337:1337
    networks:
      - frontend
      - backend

  app-frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./services/frontend:/app
    ports:
      - 8000:80
    networks:
      - frontend

  db-backend:
    image: postgres
    restart: always
    volumes:
      - db-data-backend:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sails
      POSTGRES_DB: sails
      POSTGRES_PASSWORD: sails
    networks:
      - backend

  redis:
    image: redis:latest
    volumes:
      - redis-storage:/data
    entrypoint: ["redis-server", "--appendonly", "yes"]
    restart: always
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8025:8025
    networks:
      - frontend

volumes:
  db-data-backend:
  redis-storage:

networks:
  backend:
  frontend:
