version: '3.7'
services:

  app:
    image: docker.io/jetalone/ogl-application:61
    ports:
      - 1337:8080

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']

  db:
    image: postgres
    restart: always
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sails
      POSTGRES_DB: sails
      POSTGRES_PASSWORD: sails

  redis:
    image: redis
    restart: always
      
volumes:
  db-storage:
  