name: Build and publish Docker Image

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
    - uses: actions/checkout@master
    - name: Publish Front to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jetalone/opengame-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./services/frontend
        dockerfile: ./services/frontend/Dockerfile
        snapshot: true
        tag_names: true

    - uses: actions/checkout@master
    - name: Publish Backend to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jetalone/opengame-backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./services/backend
        dockerfile: ./services/backend/Dockerfile
        snapshot: true
        tag_names: true
